version: '3.8'
services:

  mysql:
    image: mysql:5.7
    container_name: mysql-go-api
    command: 
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --sql-mode=ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    environment:
        MYSQL_ROOT_USER: ${DB_ROOT_USER}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASS}
        TZ: 'Asia/Tokyo'
    ports: 
        - "3306:3306"
    volumes:
        - db-volume:/var/lib/mysql

volumes:
  db-volume:
