version: '3'
services:

  mysql:
    image: mysql:8.3
    container_name: mysql-go-api
    command: 
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
    environment:
        MYSQL_ROOT_USER: ${DB_ROOT_USER}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASS}
        TZ: ${DB_TIMEZONE}
        LAND: ${DB_LAND}
    platform: linux/x86_64
    ports: 
        - "3306:3306"
    volumes:
        - ./_development/data:/var/lib/mysql
